
site_name: Deeplyn Backend Documentation

theme:
  name: material

  features:
    - navigation.tabs       
    - navigation.sections    
    - search.suggest         
    - content.code.copy
  palette:
   
    - scheme: default
      primary: indigo
      accent: indigo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            
            show_symbol_type_heading: true
            show_signature: true
            show_source: true
            docstring_section_style: table
            show_category_heading: false

nav:
  - Home: index.md
  - Users app:
    - Overview: users/overview.md
    - Models: users/models.md
    - Views: users/views.md