# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('vector_index', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Emotion',
                'verbose_name_plural': 'Emotions',
                'db_table': 'emotions',
                'ordering': ['vector_index'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'db_table': 'journals',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_encrypted', models.BinaryField()),
                ('title_iv', models.BinaryField(max_length=12)),
                ('content_encrypted', models.BinaryField()),
                ('content_iv', models.BinaryField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('emotions_source', models.CharField(choices=[('none', 'None'), ('manual', 'Manual'), ('transformer', 'AI Transformer')], default='none', max_length=15)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='journal.journal')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ['-is_favorite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('transformer', 'AI Transformer')], max_length=15)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_emotions', to='journal.emotion')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_emotions', to='journal.note')),
            ],
            options={
                'verbose_name': 'Note Emotion',
                'verbose_name_plural': 'Note Emotions',
                'db_table': 'note_emotions',
                'constraints': [models.CheckConstraint(condition=models.Q(('intensity__gte', 0.0), ('intensity__lte', 1.0)), name='intensity_range')],
                'unique_together': {('note', 'emotion')},
            },
        ),
    ]
