# Generated by Django 5.2.13 on 2026-04-26 12:43

from django.db import migrations

EMOTIONS = [
    (0,  "admiration"),
    (1,  "amusement"),
    (2,  "anger"),
    (3,  "annoyance"),
    (4,  "approval"),
    (5,  "caring"),
    (6,  "confusion"),
    (7,  "curiosity"),
    (8,  "desire"),
    (9,  "disappointment"),
    (10, "disapproval"),
    (11, "disgust"),
    (12, "embarrassment"),
    (13, "excitement"),
    (14, "fear"),
    (15, "gratitude"),
    (16, "grief"),
    (17, "joy"),
    (18, "love"),
    (19, "nervousness"),
    (20, "optimism"),
    (21, "pride"),
    (22, "realization"),
    (23, "relief"),
    (24, "remorse"),
    (25, "sadness"),
    (26, "surprise"),
    (27, "neutral"),
]

def populate_emotions(apps, schema_editor):
    Emotion = apps.get_model('journal', 'Emotion')
    for vector_index, name in EMOTIONS:
        Emotion.objects.create(vector_index=vector_index, name=name)

def depopulate_emotions(apps, schema_editor):
    Emotion = apps.get_model('journal', 'Emotion')
    Emotion.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_emotions, depopulate_emotions),
    ]