# Generated by Django 5.2.13 on 2026-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_populate_emotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_iv',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title_iv',
        ),
        migrations.AlterField(
            model_name='note',
            name='emotions_source',
            field=models.CharField(choices=[('none', 'None'), ('manual', 'Manual'), ('transformer', 'Automatically')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='noteemotion',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('transformer', 'Automatically')], max_length=15),
        ),
    ]
