# Generated by Django 5.2.13 on 2026-05-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_note_content_iv_remove_note_title_iv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_encrypted',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title_encrypted',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='note',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
