# Generated by Django 5.2.13 on 2026-05-12 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_remove_note_content_encrypted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=1500)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes_as_client', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_copies', to='journal.note')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes_as_therapist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_notes',
                'unique_together': {('note', 'therapist')},
            },
        ),
    ]
