# Generated by Django 5.2.13 on 2026-05-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_sharednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednote',
            name='emotions_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sharednote',
            name='emotions_source',
            field=models.CharField(choices=[('none', 'None'), ('manual', 'Manual'), ('transformer', 'Automatically')], default='none', max_length=15),
        ),
    ]
