from django.core.management.base import BaseCommand
from quiz.models import QuizQuestion

PREDEFINED_QUESTIONS = [
    "What is one thing you noticed about your body right now?",
    "What emotion are you feeling in this exact moment?",
    "Describe your surroundings using only your five senses.",
    "What sounds can you hear right now if you pause and listen?",
    "What were you thinking about just before opening this quiz?",
    "Can you name three things you can see, two you can hear, and one you can touch?",
    "What does your breathing feel like right now - fast, slow, shallow, deep?",
    "What is one thought that keeps coming back to you today?",
    "How does your body feel right now - tense, relaxed, tired, energized?",
    "What is one thing you did today without really paying attention to it?",
    "If you could describe your current mood as a weather pattern, what would it be?",
    "What is one thing you ate today, and can you remember how it tasted?",
    "What physical sensation are you most aware of right now?",
    "What is one thing you are grateful for in this moment?",
    "Did you notice any moment today where you were fully present? What were you doing?",
    "What is one judgment you made about yourself today? Can you observe it without reacting?",
    "What was the first thing you felt when you woke up this morning?",
    "If you close your eyes for 10 seconds, what do you notice?",
    "What is one repetitive thought pattern you noticed today?",
    "How would you describe your energy level right now on a scale of 1-10?",
    "What is one thing happening in your body that you usually ignore?",
    "What emotion did you feel most frequently today?",
    "What is one thing you can appreciate about this exact moment?",
    "Did you catch yourself on autopilot today? When?",
    "What is one worry about the future that crossed your mind today?",
    "What is one regret about the past that you thought about today?",
    "Can you sit with your current feeling for 30 seconds without trying to change it?",
    "What does the air feel like on your skin right now?",
    "What is one kind thing you did for yourself today, no matter how small?",
    "If your emotions right now had a color, what would it be?",
    "What is one thing you noticed about someone else today?",
    "How does your jaw feel right now - clenched or relaxed?",
    "What is one moment today where time seemed to slow down?",
    "What is one thing you can hear that you were not aware of before pausing?",
    "What is the texture of what you are sitting or lying on right now?",
    "What is one thing you tasted today that you actually paid attention to?",
    "How are your shoulders feeling right now?",
    "What is one pleasant thing that happened today that you almost overlooked?",
    "What is one thought you are having right now that is not a fact, just an opinion?",
    "If you scan your body from head to toe, where do you feel the most tension?",
    "What is one smell you noticed today?",
    "What was the last thing that made you smile, even briefly?",
    "What is one task you did mindfully today - with full attention?",
    "Did you notice any urge today that you chose not to act on?",
    "What is the temperature of the room you are in right now?",
    "What is one assumption you made about someone today?",
    "What is one thing your body is telling you right now that you usually ignore?",
    "Can you name the emotion you are feeling without labeling it as good or bad?",
    "What is one moment today when you felt truly calm?",
    "What is one thing you see right now that you find beautiful or interesting?",
    "How does your stomach feel right now?",
    "What is one thing you heard someone say today that stuck with you?",
    "If your mind were a room, how cluttered or organized would it be right now?",
    "What is one thing you touched today that had an interesting texture?",
    "What emotion are you trying to avoid right now?",
    "What is one thing you can let go of right now?",
    "How fast are your thoughts moving right now?",
    "What is one moment today where you felt connected to someone?",
    "What is one thing you are holding onto that no longer serves you?",
    "Did you notice any moment today where you stopped and took a deep breath?",
    "What is the quality of light around you right now?",
    "What is one thing your hands have done today?",
    "If you had to describe your day in one word, what would it be?",
    "What is one place in your body where you feel your emotions most?",
    "What is one thing you can forgive yourself for today?",
    "What did you notice about your walking today - pace, posture, direction?",
    "What is one expectation you had today that did not match reality?",
    "What is one moment today when you were kind without thinking about it?",
    "How are your eyes feeling right now - tired, alert, heavy?",
    "What is one thing you would like to let your mind rest from?",
    "What are you most aware of in your environment right now?",
    "What is one thing about today that surprised you?",
    "What is one sensation in your body that feels comfortable right now?",
    "If you could freeze one moment from today, which one would it be?",
    "What is one thing you are putting pressure on yourself about?",
    "How does your chest feel right now?",
    "What is one thing you did today just because you wanted to, not because you had to?",
    "What is one thought you can observe right now without getting caught up in it?",
    "What is one thing about your current environment that you have never noticed before?",
    "What is the pace of your life right now - rushing, steady, or stagnant?",
    "What is one thing you are curious about right now?",
    "What was the most vivid sensory experience you had today?",
    "How present do you feel on a scale of 1-10 right now?",


    # DISTRESS TOLERANCE (83 quizzes)
    # focus: crisis, impulsivness, pain tollerance
 
    "What is the most difficult moment you faced today, and how did you get through it?",
    "When you felt overwhelmed today, what was the first thing you wanted to do?",
    "Did you have any urge today that you managed to resist? How?",
    "What is one thing you can do right now to soothe yourself?",
    "What coping strategy did you use today when things got hard?",
    "If your distress right now were on a scale of 1-10, where would it be?",
    "What is one crisis you survived in the past that felt impossible at the time?",
    "What would you tell a friend who was feeling exactly how you feel right now?",
    "What is one thing you can do in the next 5 minutes to take care of yourself?",
    "When you feel like everything is falling apart, what is one thing that stays stable?",
    "What is one distraction that actually helps you when you are in pain?",
    "Did anything today push you close to your emotional limit? What happened?",
    "What is one way you can comfort yourself that does not involve anyone else?",
    "What is one thing you survived this week that you did not think you could?",
    "How did you handle disappointment today?",
    "What is one healthy way you dealt with frustration recently?",
    "When was the last time you felt completely overwhelmed, and what helped?",
    "What is one thing you can accept about today that you cannot change?",
    "What is the hardest emotion you had to sit with today?",
    "Did you use any TIPP skills today (Temperature, Intense exercise, Paced breathing, Progressive relaxation)?",
    "What is one situation today where walking away was the best choice?",
    "What is one thing that helps you calm down when you feel like exploding?",
    "What is one thing you would do differently if today's hardest moment happened again?",
    "When you felt triggered today, how long did the intensity last?",
    "What is one way you can make this moment slightly more bearable?",
    "What is one thought that helps you get through tough times?",
    "Did you use any grounding techniques today? Which ones?",
    "What is one physical activity that helps you release tension?",
    "What is one place you can go to feel safe when everything feels chaotic?",
    "What is one song, show, or activity that distracts you in a healthy way?",
    "How did you take care of yourself after a difficult interaction today?",
    "What is one thing you tolerated today that was uncomfortable but not dangerous?",
    "When you feel like giving up, what is one reason to keep going?",
    "What is one way you soothed yourself without making the situation worse?",
    "Did you notice the urge to act impulsively today? What happened?",
    "What is one consequence you avoided today by pausing before acting?",
    "What is one way you can reward yourself for getting through a hard day?",
    "What is one thing you can control right now, even if everything else feels out of control?",
    "How did you handle waiting for something today? Was it hard?",
    "What is one situation today where you chose to tolerate discomfort instead of reacting?",
    "What is one coping skill you wish you had used today?",
    "When did you last feel truly safe? What made it feel that way?",
    "What is one thing about this difficult time that will not last forever?",
    "Did you try any self-soothing with your five senses today?",
    "What is one commitment you can make to yourself for tomorrow?",
    "What is one problem you are facing that you can take one small step toward solving?",
    "What is one thing you accepted today instead of fighting against it?",
    "How do you usually react when things do not go your way? Did that happen today?",
    "What is one alternative behavior you can try next time you feel the urge to self-destruct?",
    "What is one affirmation that helps you when you feel hopeless?",
    "Did you set any boundaries today to protect your mental health?",
    "What is one crisis from the past that taught you something valuable?",
    "What is one way you can be gentle with yourself right now?",
    "What would your future self thank you for doing or not doing today?",
    "What is one thing you are proud of yourself for tolerating today?",
    "How long did your most intense emotion last today?",
    "What is one thing you can do to make your environment more calming right now?",
    "When you felt pain today, did you try to push it away or sit with it?",
    "What is one way you can prepare for a difficult moment you see coming?",
    "What is one positive outcome that came from a painful experience in your past?",
    "Did you notice any all-or-nothing thinking today? What was it about?",
    "What is one thing that gives you hope, even on your worst days?",
    "What is one thing you can do tonight to set yourself up for a better tomorrow?",
    "When you felt the urge to do something harmful, what stopped you?",
    "What is one person, place, or thing that makes you feel grounded?",
    "What is one skill you have used before that actually worked in a crisis?",
    "What is one way you showed courage today?",
    "Did anything today feel unbearable? How did you survive it?",
    "What is one small act of self-care you can do before bed tonight?",
    "What is one thing you are learning about yourself through difficult times?",
    "What is one promise you can make to yourself for the next hour?",
    "What is the difference between how you feel right now and how you felt this morning?",
    "What is one thing you endured today that you could not have endured a year ago?",
    "What is one thing you need right now that you are not giving yourself?",
    "Did you try the opposite action to any urge today?",
    "What is one way you handled rejection or criticism today?",
    "What is one thing that was hard today but worth doing?",
    "What is one emotion you wish you could turn down the volume on?",
    "What is one thing you can do right now to feel 1% better?",
    "What was the peak of your emotional pain today, and what was the lowest point?",
    "What is one moment today when you chose patience over reaction?",
    "What is one way you proved to yourself that you are stronger than you think?",

   
    # EMOTION REGULATION (84)
    # focus: identifing, understanding si emotion management
  
    "What emotion did you feel the most intensely today?",
    "What triggered your strongest emotion today?",
    "How did your emotions change throughout the day?",
    "What is one emotion you felt today that surprised you?",
    "Can you name the emotion you are feeling right now without judging it?",
    "What is one situation today where your emotional reaction did not match the situation?",
    "What is one emotion you tend to avoid? Did it show up today?",
    "How intense was your strongest emotion today on a scale of 1-10?",
    "What is one emotion you felt today that you wish lasted longer?",
    "What is one emotion you felt today that you wish had been less intense?",
    "Did you notice any secondary emotions today - an emotion about an emotion?",
    "What physical sensations came with your strongest emotion today?",
    "What is one thing that always makes you feel a certain emotion, and did it happen today?",
    "How long did your most intense emotion last before it started to fade?",
    "What is one emotion you are comfortable feeling? What is one you are not?",
    "Did you eat, sleep, and move enough today? How did that affect your emotions?",
    "What is one thing you could have done differently to manage a difficult emotion today?",
    "When you felt a strong negative emotion today, what was your first impulse?",
    "What is one positive emotion you experienced today, even briefly?",
    "Did any past experience influence how you felt about something today?",
    "What is one emotion that felt overwhelming today, and what did you do about it?",
    "What is one way your emotions affected your decisions today?",
    "What is one thing you can do to increase positive emotions tomorrow?",
    "Did you notice any patterns in your emotions this week?",
    "What is one situation today where you successfully regulated a strong emotion?",
    "What is one thing that made you feel vulnerable today?",
    "How did your mood when you woke up compare to your mood right now?",
    "What is one emotion you felt today that you have trouble naming?",
    "What is one way your emotions affected your relationships today?",
    "Did you do anything today specifically to improve your mood? Did it work?",
    "What is one thing that reliably shifts your mood in a positive direction?",
    "What is one emotional need you have that was not met today?",
    "How did stress affect your emotions today?",
    "What is one thing you learned about your emotional patterns today?",
    "Did you experience any emotional numbness today? What was happening?",
    "What is one emotion you felt today that you usually suppress?",
    "What is one way you can practice self-compassion about how you felt today?",
    "What is one boundary you need to set to protect your emotional health?",
    "Did you experience any rapid mood changes today? What preceded them?",
    "What is one thing that made you feel emotionally safe today?",
    "What is one emotion you want to feel more of? What can you do to invite it?",
    "How did your interactions with others affect your emotional state today?",
    "What is one coping strategy you used today for an uncomfortable emotion?",
    "What is one emotion you are carrying from yesterday into today?",
    "Did you notice any emotion that came from a thought rather than an event?",
    "What is one way you expressed your emotions today - healthy or unhealthy?",
    "What is one thing that helped you feel in control of your emotions today?",
    "What is one emotion you felt today that you would like to understand better?",
    "How did your expectations for today affect your emotional experience?",
    "What is one thing that made you feel proud of how you handled your emotions today?",
    "Did any small thing trigger a big emotional reaction today? What happened?",
    "What is one thing you can forgive yourself for feeling today?",
    "What is one way your body warned you about a rising emotion today?",
    "What is one thing you can do tonight to reset your emotional state?",
    "Did loneliness affect you today? How did you respond?",
    "What is one emotion you shared with someone today?",
    "What is one way you numbed your emotions today - screens, food, sleep?",
    "What is one emotion that feels comfortable and familiar, even if it is painful?",
    "What is one thing you can plan for tomorrow to protect your emotional wellbeing?",
    "Did you experience jealousy or envy today? What triggered it?",
    "What is one thing that shifted your mood unexpectedly today?",
    "What is one emotion you felt today that connects to a deeper need?",
    "How did tiredness or hunger affect your emotions today?",
    "What is one way you can validate your own emotions right now?",
    "What is one thing you resisted doing today because of how you felt?",
    "What is one emotion that came and went quickly today?",
    "What is one thing that always triggers sadness for you? Did it come up today?",
    "What is one thing that always triggers anger for you? Did it come up today?",
    "What is one thing that always triggers anxiety for you? Did it come up today?",
    "Did you experience any joy today? What created it?",
    "What is one thing you need to emotionally process from today?",
    "How would you rate your overall emotional balance today on a scale of 1-10?",
    "What is one emotion you noticed in someone else today?",
    "What is one way you can be kinder to yourself about your emotions?",
    "Did guilt play a role in your day? Was it justified or unjustified?",
    "What is one emotion that kept returning throughout the day?",
    "What is one thing you want to feel tomorrow that you did not feel today?",
    "What is one way you can celebrate a small emotional win from today?",
    "Did shame show up for you today? What was it about?",
    "What is one thing that always helps you feel loved or cared for?",
    "What is one pattern between your thoughts and emotions that you noticed today?",
    "How did social media or news affect your emotions today?",
    "What is one healthy way you released an intense emotion today?",
    "What is one emotion from today that you want to explore further?",
    "What is one step you can take toward emotional balance right now?",

  
    # INTERPERSONAL EFFECTIVENESS (84)
    # focus: relationships, comunication, bounderies, conflicts
  
    "Who did you interact with today, and how did it make you feel?",
    "Did you have a difficult conversation today? How did you handle it?",
    "What is one boundary you maintained or set today?",
    "Did you say yes to something today when you wanted to say no?",
    "Did you say no to something today? How did it feel?",
    "What is one relationship in your life that felt supportive today?",
    "What is one relationship that caused you stress today?",
    "Did you express a need to someone today? How did they respond?",
    "What is one way you could have communicated more clearly today?",
    "Did you feel heard by anyone today? What made the difference?",
    "What is one thing someone did today that affected your mood?",
    "Did you avoid any conversation or person today? Why?",
    "What is one compliment you could give someone right now?",
    "Did you feel judged by anyone today? How did you cope?",
    "What is one thing you wished you had said today but did not?",
    "How did you handle a disagreement or conflict today?",
    "What is one thing someone did today that you are thankful for?",
    "Did you feel lonely in any interaction today, even with people around?",
    "What is one way you showed kindness to someone today?",
    "Did anyone cross a boundary of yours today? What happened?",
    "What is one thing you need from your relationships that you are not getting?",
    "Did you compare yourself to anyone today? How did it affect you?",
    "What is one thing you admire about someone in your life?",
    "Did you try to people-please today? In what situation?",
    "What is one relationship where you feel safe being yourself?",
    "Did you feel the need to explain or justify yourself to someone today?",
    "What is one way you can show appreciation to someone tomorrow?",
    "Did you receive any feedback today? How did you react?",
    "What is one thing you would like to change about how you interact with others?",
    "Did you experience rejection or fear of rejection today?",
    "What is one healthy way you handled a social situation that usually stresses you?",
    "What is one thing someone said to you today that you keep replaying in your mind?",
    "Did you ask for help today? Was it hard?",
    "What is one relationship pattern you noticed today - good or bad?",
    "Did you feel invisible or overlooked by anyone today?",
    "What is one way you validated someone else's feelings today?",
    "Did you feel the urge to push someone away today? What was behind it?",
    "What is one conflict you are avoiding right now? What makes it scary?",
    "Did anyone make you feel important today? Who and how?",
    "What is one thing you can do to strengthen a relationship this week?",
    "Did you experience any miscommunication today? What went wrong?",
    "What is one thing you learned about yourself from an interaction today?",
    "Did you feel the need to control how someone perceived you today?",
    "What is one way you practiced assertiveness today?",
    "Did guilt influence how you treated someone today?",
    "What is one conversation you are dreading? What makes it hard?",
    "Did you feel trusted by anyone today? How did you know?",
    "What is one way someone showed they cared about you today?",
    "Did you pretend to feel something you did not today? In what situation?",
    "What is one way you can take responsibility for your part in a difficult interaction?",
    "Did you feel the pull to isolate yourself today? What triggered it?",
    "What is one way you can be a better listener tomorrow?",
    "Did you feel competitive with anyone today? About what?",
    "What is one thing you need to forgive someone for?",
    "Did you feel the need to rescue or fix someone today?",
    "What is one boundary you want to set but have not yet?",
    "How did your self-image affect your interactions today?",
    "Did you share something vulnerable with anyone today? How did it go?",
    "What is one relationship where you give more than you receive?",
    "Did you feel like you had to perform or put on a mask today?",
    "What is one social skill you would like to improve?",
    "Did you feel grateful for anyone in your life today? Who?",
    "What is one thing you want someone in your life to understand about you?",
    "Did you experience any passive-aggressive behavior today - from yourself or others?",
    "What is one thing you can do to feel more connected to others?",
    "Did fear of abandonment influence any of your actions today?",
    "What is one way you can practice healthy attachment in your relationships?",
    "Did you feel suffocated or controlled by anyone today?",
    "What is one interaction today that went better than expected?",
    "Did you feel the urge to test someone's loyalty or love today?",
    "What is one way you showed respect to someone today?",
    "Did you avoid eye contact with anyone today? Why?",
    "What is one thing you can do to repair a damaged relationship?",
    "Did you feel like you belonged somewhere today?",
    "What is one way you contributed to a positive interaction today?",
    "Did you hold back your opinion to keep the peace today? How do you feel about it?",
    "What is one thing you can communicate more openly about?",
    "Did you feel emotionally safe in any conversation today?",
    "What is one thing someone did today that hurt, even if they did not mean to?",
    "What is one relationship in your life that challenges you to grow?",
    "Did you practice any DEAR MAN skills today (Describe, Express, Assert, Reinforce)?",
    "What is one way you can prioritize your own needs in relationships?",
    "Did you feel the urge to apologize when you did nothing wrong?",
    "What is one thing you value most in a friendship or relationship?",

  
    # COGNITIVE RESTRUCTURING - CBT (83)
    # focus: thinking, cognitive distortions, perspective
   
    "What is one negative thought you had about yourself today?",
    "Is the thought you had based on facts or on feelings?",
    "What is one thing you told yourself today that was not entirely true?",
    "Did you catch yourself catastrophizing today - imagining the worst outcome?",
    "What is one thing you predicted would go badly today? Did it actually go badly?",
    "Did you take anything personally today that might not have been about you?",
    "What is one thing you are telling yourself right now that a friend would disagree with?",
    "Did you use any all-or-nothing language today - always, never, everyone, no one?",
    "What is one thing you believe about yourself that you have never questioned?",
    "If your best friend had your exact day, what would you tell them?",
    "What is one automatic negative thought you noticed today?",
    "Did you jump to any conclusions today without having all the facts?",
    "What is one thought that made you feel worse than the situation warranted?",
    "What evidence supports your most negative thought today? What evidence goes against it?",
    "Did you label yourself negatively today - stupid, worthless, unlovable?",
    "What is one more balanced way to think about what happened today?",
    "Did you mind-read today - assume you knew what someone was thinking?",
    "What is one belief you have about yourself that limits you?",
    "Did you discount any positive experiences today? Why?",
    "What is one thing you accomplished today, no matter how small?",
    "What is one thought pattern you would like to break?",
    "Did you blame yourself for something that was not entirely your fault today?",
    "What is one thing you are afraid of that has a low chance of happening?",
    "What would a kinder inner voice say about your day?",
    "Did you use emotional reasoning today - I feel it, so it must be true?",
    "What is one strength you used today that you tend to overlook?",
    "Did you overgeneralize today - one bad thing means everything is bad?",
    "What is one thing you would say to your younger self about today?",
    "What is one way your thinking changed from morning to evening today?",
    "Did you should yourself today - I should be better, I should have done more?",
    "What is one opinion you have about yourself that you formed based on limited experience?",
    "What is one positive thing about yourself that you have difficulty believing?",
    "Did you compare your worst to someone else's best today?",
    "What is one thought you had today that you chose not to believe?",
    "What is one assumption about the future that is causing you anxiety?",
    "Did you personalize anything today - assume something bad was your fault?",
    "What is one way you were too hard on yourself today?",
    "What is one thought you repeated many times today? Is it helpful?",
    "If you could rewrite one thought from today, what would the new version be?",
    "What is one thing you are certain about that might actually be an assumption?",
    "Did you filter out the good and focus only on the bad today?",
    "What is one thing that went right today that your mind tried to minimize?",
    "What is one standard you hold yourself to that no one else expects of you?",
    "Did you catastrophize about your health, relationships, or future today?",
    "What is one fear-based thought that controlled your behavior today?",
    "What is one thought you can challenge right now with evidence?",
    "Did you use magnification or minimization today?",
    "What is one belief about relationships that might not be accurate?",
    "What is one thing you told yourself today that you would never say to a friend?",
    "Did you have any intrusive thoughts today? How did you handle them?",
    "What is one way your past is influencing how you see today?",
    "What is one new perspective you can try on a problem you are facing?",
    "Did you assume the worst about someone's intentions today?",
    "What is one thing you are dreading that might actually turn out fine?",
    "What is one cognitive distortion you recognize as your go-to pattern?",
    "Did any thought today trigger a strong emotional reaction?",
    "What is one way you can practice self-compassion in your thinking?",
    "Did you set unrealistic expectations for yourself today?",
    "What is one thing you can reframe from a failure to a learning experience?",
    "What is one automatic thought you had today that you caught and questioned?",
    "Did you notice any black-and-white thinking today?",
    "What is one thing you would think differently about if you were less anxious?",
    "What is one thing you did today that proves you are more capable than you think?",
    "Did you confuse a feeling with a fact today?",
    "What is one way your inner critic showed up today?",
    "What is one thing you can remind yourself of when negative thoughts spiral?",
    "Did you notice any fortune-telling today - predicting bad outcomes?",
    "What is one thought that would help you sleep better tonight?",
    "What is one thing you believe you deserve that your thoughts try to deny?",
    "Did you blame anyone entirely for something that had multiple causes?",
    "What is one thing you think about yourself that you would never think about someone else?",
    "What is one thing you know is true about yourself, even when your thoughts say otherwise?",
    "Did you notice your thoughts racing today? What were they about?",
    "What is one area of your life where your thinking is most distorted?",
    "What is one way you can practice thought defusion - seeing thoughts as just thoughts?",
    "What is one helpful thought you can carry into tomorrow?",
    "Did you beat yourself up mentally today? About what?",
    "What is one thing you learned about your thinking patterns today?",
    "What is one thought you are ready to let go of?",
    "What is one way your thoughts do not define who you actually are?",
    "What is one thing you would think if you believed you were enough?",
    "Did your thoughts today help you or hold you back?",
    "What is one small shift in thinking that could make tomorrow better?",

   
    # BEHAVIORAL ACTIVATION - CBT (83)
    # focus: actions, motivation, habits, change
  
    "What is one thing you did today that gave you a sense of accomplishment?",
    "What is one activity you avoided today because of how you felt?",
    "What is one thing you can do tomorrow that usually makes you feel better?",
    "Did you leave the house today? How did it affect your mood?",
    "What is one small task you completed today that you almost skipped?",
    "What is one hobby or interest you have not engaged with recently? Why?",
    "What is one thing you used to enjoy that you have stopped doing?",
    "Did you move your body today? How did it make you feel?",
    "What is one thing you procrastinated on today? What got in the way?",
    "What is one positive habit you maintained today?",
    "What is one new thing you tried today, even if it was small?",
    "What is one thing you can add to your routine that brings you joy?",
    "Did you do anything creative today? If not, what could you try?",
    "What is one goal you worked toward today?",
    "What is one thing you did today just for fun, with no purpose?",
    "Did you take care of your basic needs today - food, water, hygiene, rest?",
    "What is one thing you are avoiding that you know would help if you did it?",
    "What is one activity that always improves your mood?",
    "Did you spend any time in nature today?",
    "What is one thing you can plan for this week that excites you?",
    "What is one routine you follow that supports your mental health?",
    "Did you reach out to anyone today? How did it go?",
    "What is one skill you practiced today?",
    "What is one thing you can do right now that takes less than 5 minutes and feels good?",
    "Did you rest intentionally today, or did you collapse from exhaustion?",
    "What is one thing you did today that your future self will thank you for?",
    "What is one small step you can take toward a big goal?",
    "Did you laugh today? What made you laugh?",
    "What is one thing you did today that was outside your comfort zone?",
    "What is one thing that gave you energy today?",
    "What is one thing that drained your energy today?",
    "Did you stick to any plan or schedule today?",
    "What is one act of kindness you performed today?",
    "What is one thing you can do tomorrow morning to start the day well?",
    "Did you engage in any unhealthy coping behavior today? What could replace it?",
    "What is one thing you are looking forward to?",
    "What is one way you took responsibility for your wellbeing today?",
    "Did you practice any self-care today? What kind?",
    "What is one thing you learned today?",
    "What is one change you made recently that is working well?",
    "What is one reward you can give yourself for something you did well today?",
    "Did you spend time on something meaningful to you today?",
    "What is one behavior you want to increase in your daily life?",
    "What is one behavior you want to decrease in your daily life?",
    "What is one way you structured your day that helped you feel stable?",
    "Did you do anything today that aligned with your values?",
    "What is one thing you can prepare tonight for a better day tomorrow?",
    "What is one social activity you can plan for this week?",
    "Did you celebrate any small win today?",
    "What is one thing you did today that required effort but was worth it?",
    "What is one area of your life where you feel stuck? What is one tiny action you could take?",
    "Did you set any intentions for today? Did you follow through?",
    "What is one healthy meal you ate today or can plan for tomorrow?",
    "What is one thing you did today that was different from your usual pattern?",
    "Did you express gratitude to anyone today? How?",
    "What is one thing you can commit to doing every day this week?",
    "Did you listen to music today? How did it affect your mood?",
    "What is one way you can make your living space more pleasant?",
    "What is one phone call, message, or email you have been putting off?",
    "Did you drink enough water today?",
    "What is one thing you did today that was brave?",
    "What is one responsibility you fulfilled today?",
    "Did you read, watch, or learn anything interesting today?",
    "What is one morning habit you can build that takes 2 minutes?",
    "What is one evening habit you can build that helps you wind down?",
    "What is one thing you organized or cleaned today?",
    "Did you spend time doing something you feel passionate about?",
    "What is one way you took initiative today?",
    "What is one thing you finished today that had been hanging over you?",
    "Did you set any boundaries today that protected your time or energy?",
    "What is one pleasant activity you can schedule for this weekend?",
    "What is one thing you want to start doing but keep postponing?",
    "Did you help someone today? How did it feel?",
    "What is one thing you can do differently tomorrow compared to today?",
    "What is one simple pleasure you experienced today?",
    "Did you work toward any long-term goal today?",
    "What is one thing you can do to sleep better tonight?",
    "What is one healthy decision you made today?",
    "Did you take any breaks today when you needed them?",
    "What is one way you can be more active tomorrow?",
    "What is one thing you kept putting off today but finally did?",
    "What is one positive action you can take in the next hour?",
    "What is one way you showed up for yourself today?",
]


class Command(BaseCommand):
    help = 'populate database'
    def handle(self, *args, **options):
        created_count = 0
        skipped_count = 0

        for text in PREDEFINED_QUESTIONS:
            already_exists = QuizQuestion.objects.filter(text=text,is_predefined=True).exists()

            if already_exists:
                skipped_count += 1
                continue

            QuizQuestion.objects.create(text=text,is_predefined=True,created_by=None)
            created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Done! Created: {created_count}, Skipped (already exist): {skipped_count}, '
                f'Total predefined in DB: {QuizQuestion.objects.filter(is_predefined=True).count()}'
            )
        )
