# Generated by Django 5.2.13 on 2026-05-28 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPendingClient',
            fields=[
            ],
            options={
                'verbose_name': 'session_client_approval',
                'verbose_name_plural': 'sessions_client_approval',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('therapy.session',),
        ),
        migrations.CreateModel(
            name='SessionPendingTherapist',
            fields=[
            ],
            options={
                'verbose_name': 'session_therapist_approval',
                'verbose_name_plural': 'sessions_therapist_approval',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('therapy.session',),
        ),
        migrations.AddField(
            model_name='session',
            name='need_to_approve',
            field=models.ForeignKey(blank=True, help_text='Utilizatorul care trebuie sa aprobe aceasta sesiune', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_to_approve', to=settings.AUTH_USER_MODEL),
        ),
    ]
