# Generated by Django 5.2.13 on 2026-05-29 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0006_sharednote_emotions_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('app', 'App'), ('therapist', 'Therapist')], db_index=True, default='app', max_length=10)),
                ('is_shared_by_therapist', models.BooleanField(default=False)),
                ('is_shared_by_client', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quizzes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Quiz',
                'verbose_name_plural': 'Daily Quizzes',
                'db_table': 'daily_quizzes',
            },
        ),
        migrations.CreateModel(
            name='DailyQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='', max_length=1000)),
                ('emotions_source', models.CharField(choices=[('none', 'None'), ('manual', 'Manual'), ('transformer', 'Automatically')], default='none', max_length=15)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('daily_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.dailyquiz')),
            ],
            options={
                'verbose_name': 'Daily Quiz Answer',
                'verbose_name_plural': 'Daily Quiz Answers',
                'db_table': 'daily_quiz_answers',
            },
        ),
        migrations.CreateModel(
            name='QAEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('transformer', 'Automatically')], max_length=15)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_emotions', to='quiz.dailyquizanswer')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_emotions', to='journal.emotion')),
            ],
            options={
                'verbose_name': 'QA Emotion',
                'verbose_name_plural': 'QA Emotions',
                'db_table': 'quiz_answer_emotions',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('is_predefined', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quiz_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='DailyQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('max_chars', models.PositiveIntegerField(default=500)),
                ('daily_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.dailyquiz')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_appearances', to='quiz.quizquestion')),
            ],
            options={
                'db_table': 'daily_quiz_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dailyquizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='quiz.quizquestion'),
        ),
        migrations.AddConstraint(
            model_name='dailyquiz',
            constraint=models.UniqueConstraint(fields=('client', 'date', 'source'), name='one_quiz_per_source_per_day'),
        ),
        migrations.AddConstraint(
            model_name='qaemotion',
            constraint=models.CheckConstraint(condition=models.Q(('intensity__gte', 0.0), ('intensity__lte', 1.0)), name='quiz_intensity_range'),
        ),
        migrations.AlterUniqueTogether(
            name='qaemotion',
            unique_together={('answer', 'emotion')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyquizquestion',
            unique_together={('daily_quiz', 'order'), ('daily_quiz', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyquizanswer',
            unique_together={('daily_quiz', 'question')},
        ),
    ]
