# Generated by Django 5.2.13 on 2026-05-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquiz',
            name='is_shared_by_client',
        ),
        migrations.AddField(
            model_name='dailyquizanswer',
            name='is_shared_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
