# Generated by Django 5.2.13 on 2026-06-07 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_dailyquiz_is_shared_by_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizDraftQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('max_chars', models.PositiveIntegerField(default=500)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_questions', to='quiz.quizdraft')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_appearances', to='quiz.quizquestion')),
            ],
            options={
                'db_table': 'quiz_draft_questions',
                'ordering': ['order'],
                'unique_together': {('draft', 'order'), ('draft', 'question')},
            },
        ),
    ]
