# Generated by Django 5.2.13 on 2026-06-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizdraft_quizdraftquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
