# Generated by Django 5.2.13 on 2026-06-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizquestion_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdraft',
            name='title',
        ),
    ]
