# Generated by Django 5.2.13 on 2026-04-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='resend_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
