# Generated by Django 5.2.13 on 2026-05-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clienttherapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttherapist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
