# Generated by Django 5.2.13 on 2026-06-09 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0007_update_emotions_to_17'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('dbt', 'DBT'), ('cbt', 'CBT')], db_index=True, max_length=3)),
                ('therapy_type', models.CharField(choices=[('mindfulness', 'Mindfulness'), ('distress_tolerance', 'Distress Tolerance'), ('emotion_regulation', 'Emotion Regulation'), ('interpersonal_effectiveness', 'Interpersonal Effectiveness'), ('cognitive_restructuring', 'Cognitive Restructuring'), ('behavioral_activation', 'Behavioral Activation'), ('exposure', 'Exposure'), ('problem_solving', 'Problem Solving'), ('self_monitoring', 'Self-Monitoring')], db_index=True, max_length=35)),
                ('content_format', models.CharField(choices=[('free_text', 'Free Text'), ('bullet_points', 'Bullet Points'), ('quiz_answer', 'Quiz Answer'), ('structured_reflection', 'Structured Reflection')], default='free_text', max_length=25)),
                ('nr_questions', models.PositiveSmallIntegerField(default=1)),
                ('content', models.TextField(max_length=1000)),
                ('is_predefined', models.BooleanField(db_index=True, default=False)),
                ('is_shared_by_therapist', models.BooleanField(default=False)),
                ('is_deleted_from_therapist_panel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exercises', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercises',
                'ordering': ['category', 'therapy_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, default='', max_length=1000)),
                ('comment', models.TextField(blank=True, default='', max_length=500)),
                ('emotions_source', models.CharField(choices=[('none', 'None'), ('manual', 'Manual'), ('transformer', 'Automatically')], default='none', max_length=15)),
                ('is_shared_with_therapist', models.BooleanField(default=False)),
                ('is_deleted_from_therapist_panel', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_completions', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Exercise Completion',
                'verbose_name_plural': 'Exercise Completions',
                'db_table': 'exercise_completions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('transformer', 'Automatically')], max_length=15)),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_emotions', to='exercises.exercisecompletion')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_emotions', to='journal.emotion')),
            ],
            options={
                'verbose_name': 'Exercise Emotion',
                'verbose_name_plural': 'Exercise Emotions',
                'db_table': 'exercise_emotions',
                'constraints': [models.CheckConstraint(condition=models.Q(('intensity__gte', 0.0), ('intensity__lte', 1.0)), name='exercise_intensity_range')],
                'unique_together': {('completion', 'emotion')},
            },
        ),
    ]
